# Generated by Django 2.2.2 on 2019-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField(error_messages={'unique': 'TABLE IS OCCUPIED: Kindly choose another table :)'}, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Customer_Details',
                'verbose_name_plural': 'Customer_Details',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField(blank=True, default=None)),
                ('phone_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=15)),
                ('comment', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Table_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField(blank=True, default=None)),
                ('food', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=None)),
                ('quantity', models.IntegerField(blank=True, default=None)),
                ('total', models.IntegerField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'Table_Order',
                'verbose_name_plural': 'Table_Orders',
            },
        ),
    ]
