# Generated by Django 2.2.2 on 2019-08-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('table_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('phone_no', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Customer_Order',
                'verbose_name_plural': 'Customer_Orders',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.CharField(editable=False, max_length=50)),
                ('password', models.CharField(default='abcdefgh123456789', editable=False, max_length=50)),
            ],
            options={
                'verbose_name': 'Password',
                'verbose_name_plural': 'Password',
            },
        ),
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('menu_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default=None, upload_to='images')),
                ('description', models.TextField(max_length=50)),
                ('price_per_item', models.IntegerField()),
                ('select', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Categories')),
            ],
            options={
                'verbose_name': 'Menu_item',
                'verbose_name_plural': 'Menu_Items',
            },
        ),
    ]
