# Generated by Django 2.2.2 on 2019-08-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('name', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashier',
            },
        ),
    ]
